version: "3.9"

services:
  backend:
    build:
      context: ./server
    container_name: smart-bicycle-service

    ports:
      - "8000:8000"

    volumes:
      - ./server:/app

    restart: always

  frontend:
    build:
      context: ./front2
    container_name: smart-bicycle-react

    ports:
      - "5173:5173"

    volumes:
      - ./front2:/app
      - /app/node_modules

    depends_on:
      - backend

    restart: always
