from sqlalchemy.orm import Session
from database.connection import engine, Base
from models.bike import BikeRoutesModel

# 1. DB 테이블 생성 (기존 테이블이 없다면 자동 생성)
Base.metadata.create_all(bind=engine)

# 2. 목업 데이터
ROUTES_MOCK = [
    {
        "id": "bukhansan-loop",
        "name": "북한산 순환 코스",
        "region": "서울 · 은평구",
        "regionTag": "서울",
        "difficulty": "고급",
        "bikeType": "MTB",
        "distance": "42km",
        "duration": "3h 20m",
        "rating": 4.9,
        "reviewCount": 1284,
        "image": "https://images.unsplash.com/photo-1633707167699-cdd893b84441?w=1200&q=70",
        "tags": ["고급", "MTB"],
        "departure": "북한산 국립공원 입구",
        "destination": "북한산 국립공원 입구",
        "availableBike": 8,
        "returnSpace": 12,
        "elevationGain": "1,240m",
        "maxElevation": "1,240m",
        "completionRate": 78,
        "participants": 3082,
        "season": "봄 · 가을",
        "description": "북한산 국립공원을 순환하는 험준한 산악 코스. 가파른 오르막과 시원한 내리막이 반복되는 스릴 만점의 루트.",
        "safetyTips": [
            "헬멧과 보호대를 반드시 착용하세요",
            "출발 전 GPS와 배터리를 확인하세요",
            "날씨 변화에 대비한 레이어를 준비하세요",
            "초행길은 혼자보다 그룹 라이딩을 추천해요",
        ],
        "elevationProfile": [
            {"km": 0, "elevation": 80},
            {"km": 8, "elevation": 420},
            {"km": 16, "elevation": 980},
            {"km": 21, "elevation": 1240},
            {"km": 28, "elevation": 1100},
            {"km": 35, "elevation": 650},
            {"km": 42, "elevation": 90},
        ],
    },
    {
        "id": "hangang-yeouinaru-hapjeong",
        "name": "여의나루-합정 한강 코스",
        "region": "서울 · 영등포 · 마포",
        "difficulty": "입문",
        "bikeType": "따릉이",
        "distance": "8.2km",
        "duration": "35분",
        "rating": 4.8,
        "reviewCount": 2840,
        "image": "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=1200&q=70",
        "tags": ["AI 추천", "입문"],
        "free": True,
        "departure": {"name": "여의나루역 1번출구", "available": 14, "total": 20},
        "destination": {"name": "합정역 6번출구", "available": 2, "total": 20},
        "availableBike": 14,
        "returnSpace": 2,
        "description": "한강변 자전거도로를 따라 달리는 서울 대표 따릉이 코스. 평탄한 지형으로 누구나 편하게 즐길 수 있습니다.",
    },
    {
        "id": "ttukseom-jamsil",
        "name": "뚝섬-잠실 한강 코스",
        "region": "서울 · 성동 · 송파",
        "difficulty": "입문",
        "bikeType": "따릉이",
        "distance": "12.4km",
        "duration": "55분",
        "rating": 4.7,
        "free": True,
        "image": "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=1200&q=70",
        "tags": ["입문"],
        "departure": {"name": "뚝섬유원지역 1번출구", "available": 8, "total": 15},
        "destination": {"name": "잠실역 5번출구", "available": 11, "total": 15},
    },
    {
        "id": "banpo-ichon",
        "name": "반포-이촌 한강 코스",
        "region": "서울 · 서초 · 용산",
        "difficulty": "입문",
        "bikeType": "따릉이",
        "distance": "6.8km",
        "duration": "28분",
        "rating": 4.6,
        "free": True,
        "image": "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&q=70",
        "tags": ["입문"],
        "departure": {"name": "반포한강공원 동측", "available": 0, "total": 12},
        "destination": {"name": "이촌한강공원 앞", "available": 9, "total": 12},
    },
    {
        "id": "seongsu-cafe",
        "name": "성수 카페거리 순환",
        "region": "서울 · 성동",
        "difficulty": "입문",
        "bikeType": "따릉이",
        "distance": "5.2km",
        "duration": "25분",
        "rating": 4.5,
        "free": True,
        "image": "https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=1200&q=70",
        "tags": ["입문"],
        "departure": {"name": "성수역 4번출구", "available": 12, "total": 15},
        "destination": {"name": "성수역 4번출구", "available": 12, "total": 15},
    },
    {
        "id": "namsan-loop",
        "name": "남산 순환 코스",
        "region": "서울 · 중구",
        "difficulty": "중급",
        "bikeType": "따릉이",
        "distance": "4.8km",
        "duration": "30분",
        "rating": 4.7,
        "free": True,
        "image": "https://images.unsplash.com/photo-1465447142348-e9952c393450?w=1200&q=70",
        "tags": ["중급"],
        "departure": {"name": "회현역 5번출구", "available": 7, "total": 10},
        "destination": {"name": "회현역 5번출구", "available": 7, "total": 10},
    },
    {
        "id": "hangang-full",
        "name": "한강 종주 라이딩",
        "region": "서울 · 전 구간",
        "regionTag": "서울",
        "difficulty": "중급",
        "bikeType": "로드",
        "distance": "132km",
        "duration": "6h 45m",
        "elevationGain": "380m",
        "rating": 4.8,
        "reviewCount": 3412,
        "image": "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=1200&q=70",
        "tags": ["오늘의 추천", "중급"],
        "description": "서울 전 구간을 가로지르는 한강 자전거 전용도로. 평탄한 지형으로 초보자도 도전 가능한 서울 대표 라이딩 코스입니다.",
    },
    {
        "id": "jeju-ring-road",
        "name": "제주 환상 자전거길",
        "region": "제주 · 전도",
        "regionTag": "제주",
        "difficulty": "도전",
        "bikeType": "투어링",
        "distance": "234km",
        "duration": "2박 3일",
        "elevationGain": "2,850m",
        "rating": 5,
        "reviewCount": 892,
        "image": "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&q=70",
        "tags": ["도전", "투어링"],
    },
    {
        "id": "namsan-circuit",
        "name": "남산 순환 코스",
        "region": "서울 · 중구",
        "regionTag": "서울",
        "difficulty": "입문",
        "bikeType": "도심",
        "distance": "8km",
        "duration": "45분",
        "elevationGain": "240m",
        "rating": 4.6,
        "reviewCount": 2150,
        "image": "https://images.unsplash.com/photo-1465447142348-e9952c393450?w=1200&q=70",
        "tags": ["입문", "도심"],
    },
    {
        "id": "busan-galmaetgil",
        "name": "부산 갈맷길 해안 코스",
        "region": "부산 · 해운대 ~ 송정",
        "regionTag": "부산",
        "difficulty": "중급",
        "bikeType": "로드",
        "distance": "55km",
        "duration": "4h 10m",
        "elevationGain": "680m",
        "rating": 4.7,
        "reviewCount": 976,
        "image": "https://images.unsplash.com/photo-1744802093072-dad02dd5b79d?w=1200&q=70",
        "tags": ["중급", "로드"],
    },
    {
        "id": "gyeongin-arabetgil",
        "name": "경인 아라뱃길",
        "region": "인천 · 김포 ~ 인천",
        "regionTag": "인천",
        "difficulty": "입문",
        "bikeType": "로드",
        "distance": "26km",
        "duration": "1h 40m",
        "elevationGain": "120m",
        "rating": 4.5,
        "reviewCount": 1834,
        "image": "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=1200&q=70",
        "tags": ["입문", "로드"],
    },
    {
        "id": "chuncheon-uiamho",
        "name": "춘천 의암호 순환",
        "region": "강원 · 춘천시",
        "regionTag": "강원",
        "difficulty": "중급",
        "bikeType": "그래벨",
        "distance": "35km",
        "duration": "2h 20m",
        "elevationGain": "420m",
        "rating": 4.8,
        "reviewCount": 854,
        "image": "https://images.unsplash.com/photo-1767820524140-6b94b57789b5?w=1200&q=70",
        "tags": ["중급", "그래벨"],
    },
    {
        "id": "jirisan-dulegil",
        "name": "지리산 둘레길 라이딩",
        "region": "전남 · 구례 ~ 하동",
        "regionTag": "전남",
        "difficulty": "고급",
        "bikeType": "그래벨",
        "distance": "110km",
        "duration": "8h 30m",
        "elevationGain": "2,100m",
        "rating": 4.9,
        "reviewCount": 421,
        "image": "https://images.unsplash.com/photo-1758998076258-9900be6a51f0?w=1200&q=70",
        "tags": ["고급", "그래벨"],
    },
]


def insert_mock_data():
    with Session(engine) as session:
        for item in ROUTES_MOCK:
            # 이미 존재하는 ID일 경우 무시하고 건너뜀 (중복 에러 방지)
            existing = session.get(BikeRoutesModel, item["id"])
            if existing:
                continue

            route = BikeRoutesModel(
                id=item["id"],
                name=item["name"],
                region=item["region"],
                region_tag=item.get("regionTag"),
                difficulty=item["difficulty"],
                bike_type=item["bikeType"],
                distance=item["distance"],
                duration=item["duration"],
                rating=float(item.get("rating", 0.0)),
                review_count=item.get("reviewCount", 0),
                free=bool(item.get("free", False)),
                image=item["image"],
                tags=item.get("tags"),
                departure=item.get("departure"),
                destination=item.get("destination"),
                description=item.get("description"),
                elevation_gain=item.get("elevationGain"),
                max_elevation=item.get("maxElevation"),
                completion_rate=item.get("completionRate"),
                participants=item.get("participants"),
                season=item.get("season"),
                safety_tips=item.get("safetyTips"),
                elevation_profile=item.get("elevationProfile"),
            )
            session.add(route)

        session.commit()
        print("✅ ROUTES_MOCK 데이터 INSERT 완료!")


if __name__ == "__main__":
    insert_mock_data()